"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[▌](fg:#adc6ff) $directory\
$git_branch\
$git_status\
$character
"""

[directory]
style = "fg:#e2e2e9"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = "󰊢 "
style = "fg:#bfc6dc"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:#adc6ff"
format = "([$all_status$ahead_behind]($style)) "

[character]
success_symbol = "[›](fg:#adc6ff)"
error_symbol = "[›](fg:#ffb4ab)"
vimcmd_symbol = "[‹](fg:#bfc6dc)"
