"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[▌](fg:#92ceff) $directory\
$git_branch\
$git_status\
$character
"""

[directory]
style = "fg:#e1e2e6"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = "󰊢 "
style = "fg:#b2c9df"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:#92ceff"
format = "([$all_status$ahead_behind]($style)) "

[character]
success_symbol = "[›](fg:#92ceff)"
error_symbol = "[›](fg:#ffb4ab)"
vimcmd_symbol = "[‹](fg:#b2c9df)"
