background #090A0C
foreground #E7E4DC
selection_background #28351E
selection_foreground #E7E4DC
cursor #D6A85F
cursor_text_color #090A0C
color0 #111318
color1 #C46D6D
color2 #8FA6A0
color3 #D6A85F
color4 #B59B72
color5 #B58BD4
color6 #6FC5B7
color7 #C6CBD2
color8 #4B5564
color9 #F28C98
color10 #9ADCEB
color11 #D2EE8B
color12 #A6B6ED
color13 #CEA8E8
color14 #91E0D1
color15 #E7E4DC